### PR TITLE
Update Delayed OnDoCast to save 30ms for non-koreans

### PR DESCRIPTION
**Pull request by ghost**
30 ms of attack damage!

### CODE REVIEW

**Comment by Esk0r** [comment]
tons of damage :sisi3:

**Comment by ghost** [comment]
wow shit

**Comment by L33T** [comment]
no

**Comment by zezzy** [comment]
Do you guys even dev? lol

**Comment by ghost** [comment]
Photoshoppers!

**Comment by ghost** [comment]
Get back to hacking riot @zezzy

**Comment by nabbhacker** [comment]
👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌there👌👌👌 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit

**Comment by ghost** [comment]
Hey Exory can you check your Slack private message?

**Comment by nabbhacker** [comment]
i don't even have slack lmao

**Comment by zezzy** [comment]
Can you stop making useless comments if you are not aware of the context, please? Thank you.

**Comment by nabbhacker** [comment]
Get back to hacking riot @zezzy

**Comment by ghost** [comment]
Useless comment passing by

**Comment by ghost** [comment]
:rabbit:

**Comment by ghost** [comment]
Are you triggered yet Zezzy

**Pull request closed without merging**
