### PR TITLE
Dominion fix

### PR DESCRIPTION
**Pull request by Soresu**
There is no Nexus on Dominion, so the Orbwalker will break at line 234, and it doesn't even move.
Other changes are removed spaces at the end of the line.

### CODE REVIEW

**Comment by L33T** [comment]
That's not the correct approach into fixing it, even though it does fix it. Thanks for reporting the bug.

**Comment by Soresu** [comment]
What is the correct way to fix it?

**Comment by ghost** [comment]
https://github.com/LeagueSharp/LeagueSharp.SDK/blob/master/Core/Extensions/Unit.cs#L384

Also, adding to this:
IsValidTarget() already checks for null :3

**Comment by Soresu** [comment]
As i know, if GameObjects.EnemyNexus is null, you can't cast IsValidTarget() on it. Extensions.Unit.IsValidTarget(GameObjects.EnemyNexus, GameObjects.EnemyNexus.GetRealAutoAttackRange()) would work.

**Comment by JotaBritoDev** [comment]
it's an extended method my friend =)
take a look: https://github.com/LeagueSharp/LeagueSharp.SDK/blob/master/Core/Extensions/Unit.cs#L379

so you can check it in the method, you don't need a "valid instance" to call extension methods because they are a syntax sugar to a static method...

in other words:

Nexus.IsValidTarget(range, checkTeam, from) 

is exactly the same as:

AttackableUnit.IsValidTarget(unit, range, checkTeam, from)

image
Link: https://msdn.microsoft.com/en-us/library/vstudio/bb383977(v=vs.140).aspx

**Comment by Soresu** [comment]
I'm sorry, I misread the error. It's connected to GetAutoattackRange not IsValidTarget.

**Pull request closed without merging**
