### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
wot

**Comment by ghost** [comment]
idk. i sent a request to https://github.com/LeagueSharp/LeagueSharp.Data tho. github automatically did it.

**Comment by ghost** [comment]
https://s.put.re/wwX6NtY.png

**Comment by ghost** [comment]
ah i mean https://github.com/leaguesharp-devs/LeagueSharp.SDK

**Comment by ChewyMoon** [comment]
Wat

**Comment by ghost** [comment]
can i close this one then?

**Comment by ghost** [comment]
no. i just added it. https://github.com/LeagueSharp/LeagueSharp.SDK/pull/105/commits/e49416872f49eea1ad4b76c70fbcc68cdc7d6586
and sent this request to  https://github.com/leaguesharp-devs/LeagueSharp.SDK but github automatically did something wierd

**Comment by ghost** [comment]
just tell me if i should hit merge or not :fappa:

**Comment by ghost** [comment]
of course merge it pls. it'll fix default bValue issue of MenuSliderButton

**Comment by ghost** [comment]
i don't know what https://github.com/leaguesharp-devs is. tho

**Comment by ghost** [comment]
its some 2nd sdk from some plebs :pjsalt:

**Pull request merged**
