### PR TITLE
LagFreeCircle addition

### PR DESCRIPTION
**Pull request by blm95**
Allow for developers the option to choose if they'd like support for better performing (albeit maybe worse looking) "circles", in order to give users with low-end PCs better FPS.

### CODE REVIEW

**Comment by ehmehe** [comment]
:haircut:

**Comment by ehmehe** [comment]
:dancer:

**Comment by ehmehe** [comment]
:cactus:

**Comment by ehmehe** [comment]
:baby:

**Comment by ehmehe** [comment]
:nail_care:

**Comment by ehmehe** [comment]
:pager:

**Comment by ehmehe** [comment]
:hushed:

**Comment by ehmehe** [comment]
:penguin:

**Comment by hellking298** [comment]
Stahp

**Comment by ChewyMoon** [comment]
Don't think these names for the methods are deemed "professional":

`DrawCircle2`
`DrawCircleNextLvl`

---

I do think we should merge this with the current `DrawCircle` class, probably just a property and a variable in the constructor named `LagFree` and `lagFree` respectively.

**Comment by L33T** [comment]
I will take this in consideration, but the render library is being moved out of the SDK; So this won't be merged.

**Pull request closed without merging**
