### PR TITLE
Update InterruptableSpell.cs

### PR DESCRIPTION
**Pull request by yol0swag**
plz why is this private

### CODE REVIEW

**Comment by Hellsing** [comment]
Because you would be able to modify the dictionary then ;P

**Comment by yol0swag** [comment]
That's why I changed it to private setter..

**Comment by Hellsing** [comment]
That does not mean you can't use .Clear() or .Add() and so on...

**Comment by yol0swag** [comment]
And? I'm not gonna use .Clear() or .Add() so that isn't a problem

**Comment by Hellsing** [comment]
Yo, I'm just telling you the reason why it's private :D

**Comment by Hellsing** [comment]
Just add a private field for the dictionary, set the setter to write to it and the getter to return a copy of it. Then just change all the lines which modify the property to modify the field directly instead, that would kinda solve the issue, you would need to state with a summary that it's read-only then to make sure the other devs know

**Comment by ghost** [comment]
:couple_with_heart: :octocat:

**Pull request closed without merging**
